on:
  push:
    branches: [ ftp ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Auto Deploy
    runs-on: windows-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: files.000webhost.com
        username: wedeco12
        password: Webdev_12
        protocol: ftps
        port: 21
        exclude: .git*
          - .git*/**
          - .github
        
